/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package approval.tests

class ScaryLegacySoftware {

    data class ScaryLegacyClass(val unknownValue: Map<String, String>)

    fun rollTheDice(value: Int): ScaryLegacyClass {
        return when (value) {
            0 -> ScaryLegacyClass(unknownValue = mapOf("1" to "one1"))
            1 -> ScaryLegacyClass(unknownValue = mapOf("1" to "one"))
            2 -> ScaryLegacyClass(unknownValue = mapOf("2" to "two"))
            3 -> ScaryLegacyClass(unknownValue = mapOf("3" to "three"))
            else -> ScaryLegacyClass(unknownValue = mapOf("help" to "we ran out of funding"))
        }
    }
}
